### ISSUE TITLE
Better retry logic for multiple servers

### ISSUE THREAD

**Issue by derekperkins** [ClickHouse/clickhouse-go#121]
I am using `alt_hosts` in my connection string, which works great most of the time. When there is server downtime though, usually encountered when upgrading each server in the cluster, 1/N queries will fail. In the case where there are multiple servers available, I would want to retry the same query on another server before returning an error to the caller.

> @alex-zaitsev also mentioned that you might be able to make the driver handle disconnects better.

This seems to be related to this comment in #100

**Comment by kshvakov** [comment]
Hi, I'll investigate it and try to fix this problem.

**Comment by sundarv85** [comment]
This feature would be of interest independent of it being on multiple servers or single server.. lets say if all the servers are not available, how could the library perform retries.. eventually not losing data would be very critical.. 

For e.g. NSQ defines two types of retries [here](https://nsq.io/deployment/topology_patterns.html)

>  Our libraries have two key features that help with this:
> 
> **Retries** - when your message handler indicates failure, that information is sent to nsqd in the form of a REQ (re-queue) command. Also, nsqd will automatically time out (and re-queue) a message if it hasn’t been responded to in a configurable time window. These two properties are critical to providing a delivery guarantee.
> 
> **Exponential Backoff** - when message processing fails the reader library will delay the receipt of additional messages for a duration that scales exponentially based on the # of consecutive failures. The opposite sequence happens when a reader is in a backoff state and begins to process successfully, until 0.
> In concert, these two features allow the system to respond gracefully to downstream failure, automagically.

Something like that would be possible?

**Comment by sundarv85** [comment]
We are now having three main clickhouse hosts - `host1, 2, 3`. In our program, what we do is, we create separate threads for each table insertion and each of these threads 

```
begin->prepare->(in loop exec)->commit
```

does this in a loop after reading the packets from NSQ/Kafka. The clickhouse client establishes a connection with only one of the 3 possible hosts and when that hosts goes down, our `prepare` statement fails and when this fails we start losing data. 

It matches to what is currently reported in this issue (that retry is not happening). 

Also another thought process we had is if the clickhouse library can load balance the payload to the hosts evenly.. This is because, we have 9 tables and ie. 9 threads running this begin->commit loop. If each thread can round robin the commits to each of the three hosts then it will be a more evenly distributed load balancing.. thoughts?

**Comment by sundarv85** [comment]
@kshvakov When we try to run this in production and if one of our master clickhouse servers goes down for a short while and comes back, then two things happen:

1. That payload is not sent to any other server (we lose this payload alone)
2. The client stops sending further data to this server and only uses the other servers

Any plans to fix this
