### ISSUE TITLE
Decimal: read value not valid

### ISSUE THREAD

**Issue by minaevmike** [ClickHouse/clickhouse-go#148]
Hi i am trying to read decimal value from clickhouse but it returns wrong value.
clickhouse-server: 18.16.0
Code to reproduce
```
package main

import (
	"database/sql"
	"fmt"
	"log"

	"github.com/kshvakov/clickhouse"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	checkErr(err)
	if err := connect.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			fmt.Printf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		} else {
			fmt.Println(err)
		}
		return
	}

	_, err = connect.Exec(`
		CREATE TABLE IF NOT EXISTS example (
			v Decimal(18,10)
		) engine=Memory
	`)

	checkErr(err)
	tx, err := connect.Begin()
	checkErr(err)
	stmt, err := tx.Prepare("INSERT INTO example (v) VALUES (?)")
	checkErr(err)

	if _, err := stmt.Exec(
		0.08,
	); err != nil {
		log.Fatal(err)
	}

	checkErr(tx.Commit())
	rows, err := connect.Query("SELECT v FROM example")
	checkErr(err)
	for rows.Next() {
		var (
			v               float64
		)
		checkErr(rows.Scan(&v))
		log.Printf("v: %f", v)
	}

	if _, err := connect.Exec("DROP TABLE example"); err != nil {
		log.Fatal(err)
	}
}

func checkErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
```

it would print `800000000.000000`

**Comment by kshvakov** [comment]
OK, I'll check it.

**Comment by kshvakov** [comment]
@daskol Can you check it too? ;)

**Comment by minaevmike** [comment]
seems read value must be devied to scale of decimal, because it's very strange that decimal value is only int64 https://github.com/kshvakov/clickhouse/blob/master/lib/column/decimal.go#L35

**Comment by daskol** [comment]
@kshvakov Of course.

@minaevmike Not sure. As far as I remember it is not a bug since ClickHouse wire protocol implies that decimal types are integers. From this perspective scanning result of your query to floating points reduces numerical precision. This is why changes you proposed are not fully appropriate. So it would be better to scan to `int32` or `int64` otherwise there is no any benifits to store values as decimals. Actually I was extected that nobody can scant decimals to floating points.

**Comment by daskol** [comment]
@kshvakov @minaevmike I've reproduced it. How can we escape implicit casting from integer types to floating point types subject to we must be able not to loose numerical precision?

**Comment by minaevmike** [comment]
@daskol but what profit to store integers in decimal? even if i store `1.0` current implementation would return `1e10` for this value. 
I think current implementation not correct. If i store value `1` (type `Decimal(18,5)`) and then read it from clickhouse(using `clickhouse-client`): 
```
SELECT *
FROM example

┌───────v─┐
│ 0.00001 │
└─────────┘
```
All `Decimal` values must be multiplied by scale at writing and divided at reading

**Comment by daskol** [comment]
@minaevmike No, they shouldn't. In general fixed-point numbers could have different binary representation. In this case `decimal(18,5)` means that a number could be written with precision `1e-5` and it does not exceed `1e18`. Databases like ClickHouse, PostgreSQL, MySQL and some others represent such decimals as usual 64-bits or 32-bits signed integers with a scaling factor which is scale to power of 5 in example above. The fractional part of a number is a modulo of scaling factor and the integer part is multiplied by scaling factor. This type of encoding fixed-point numbers is called decimal.

Basic arithmetics for decimals is almost the same so in the most applications one could work with decimals as ordinary integers or floats without explicit type conversion. On the other hand implicit type conversion to floating point numbers could be too obligatory. So I belive that using both `int32` and `int64` as decimals in Go is quite reasonable due to lack of built-in support.

> but what profit to store integers in decimal?

I do not understand question actually.

**Comment by minaevmike** [comment]
@daskol yeah, but in current implementation if i run code
```
_, err = connect.Exec(`
		CREATE TABLE IF NOT EXISTS example (
			v Decimal(18,5)
		) engine=Memory
	`)

	checkErr(err)
	tx, err := connect.Begin()
	checkErr(err)
	stmt, err := tx.Prepare("INSERT INTO example (v) VALUES (?)")
	checkErr(err)

	if _, err := stmt.Exec(
		1,
	); err != nil {
		log.Fatal(err)
	}
```
and then run `select * from example;` `clickhouse-client` returns value `0.00001` not `1` what i save before.

**Comment by daskol** [comment]
@minaevmike Yes, this is what should be. The column support for decimals doesn't change any integer values but the floating points.

**Comment by minaevmike** [comment]
@daskol , but i can't really understand, are you sure that this is correct?
```
package main

import (
	"database/sql"
	"fmt"
	"log"

	"github.com/kshvakov/clickhouse"
)

func main() {
	connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	checkErr(err)
	if err := connect.Ping(); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			fmt.Printf("[%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace)
		} else {
			fmt.Println(err)
		}
		return
	}

	_, err = connect.Exec(`
		CREATE TABLE IF NOT EXISTS example (
			v Decimal(18,5)
		) engine=Memory
	`)

	checkErr(err)
	tx, err := connect.Begin()
	checkErr(err)
	stmt, err := tx.Prepare("INSERT INTO example (v) VALUES (?)")
	checkErr(err)

	if _, err := stmt.Exec(
		1,
	); err != nil {
		log.Fatal(err)
	}
	if _, err := stmt.Exec(
		1.0,
	); err != nil {
		log.Fatal(err)
	}

	checkErr(tx.Commit())
	rows, err := connect.Query("SELECT v FROM example")
	checkErr(err)
	for rows.Next() {
		var (
			v               float64
		)
		checkErr(rows.Scan(&v))
		log.Printf("country: %f", v)
	}
}

func checkErr(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
```
this code would return 
```
2019/01/16 17:28:40 country: 1.000000
2019/01/16 17:28:40 country: 100000.000000
```
This is expected result???

**Comment by daskol** [comment]
@minaevmike Yes, it is. Rationale is above.

**Comment by minaevmike** [comment]
but this is inconsistent with clickhouse documentation https://clickhouse.yandex/docs/en/data_types/decimal/ 
```
SELECT toDecimal32(toInt64(2), 4) AS x

┌──────x─┐
│ 2.0000 │
└────────┘
```
but you said that it's okay if it would be `0.002`

**Comment by daskol** [comment]
@minaevmike Why it should be? How does docs on SQL stuff relate to wire transport?

**Comment by minaevmike** [comment]
@daskol i mean that if i take `int64(2)` and cast it to `decimal32(4)` i would get `2.0000` but if do the same with driver i would get value `0.0002`

**Comment by kshvakov** [comment]
In [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2) we use `github.com/shopspring/decimal` for Decimal types. See [example](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/decimal_test.go)
