### ISSUE TITLE
Inset in Array(Nullable(T)), not working. But  Array(String) DEFAULT [] is working.

### ISSUE THREAD

**Issue by hunble** [ClickHouse/clickhouse-go#337]
I had the following column which was being populated through other clickhouse clients. but not with this lib. i was getting `driver: Bad Connection` for stmt.exec block.of the insert statement.

`ALTER TABLE abc ADD COLUMN someArray Array(Nullable(String))`

so i made the string non Nullable, like following, and Inserts started to work. 
`ALTER TABLE abc ADD COLUMN someArray Array(String) DEFAULT []`

Here is the insert
```
	var stmt, err = tx.Prepare("Insert into abc (someArray) VALUES (?)")

        _, err := stmt.Exec(
		[]string{"a"},
	); 
        err != nil {
		fmt.Println(err)
	}
```

I am not sure if it is a [sqlx](https://github.com/jmoiron/sqlx) issue or [clickhouse-go](https://github.com/ClickHouse/clickhouse-go) or i just have miss understood the usage. 
Please guide me.

**Comment by lfthomaz** [comment]
I'm having the same issue with a Array(Nullable(UInt64)), although the error is different
`Syntax error (data type): failed at position 1: )\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\foffers.stock\rAr. Unmatched parentheses: )`
I think that the problem comes from the block.go code in the Read function: a column can either be an Array or a Nullable(T) but not both. I'll try to take a look into a possible solution.

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/nullable_array_test.go#L45)
