### ISSUE TITLE
Surpassing max_execution_time does not return an error

### ISSUE THREAD

**Issue by niger-prequel** [ClickHouse/clickhouse-go#804]
### Issue description
We set `max_execution_time` time to a value smaller than the query we were running. We were using the `database/sql` interface. We expected that when `rows, err := db.Query()` returns, we'd receive an error value if the query exited early due to the `max_execution_time` threshold being hit. However instead, the error is `nil` and the rows are empty. 

### Example code
```go

        func() test(connInfo ConnectionInfo) {
	    connectionString := fmt.Sprintf(
		    "tcp://%s:%s@%s:%d/%s?dial_timeout=20s&max_execution_time=60&secure=true&debug=true",
		    connInfo.Username,
		    connInfo.Password,
		    connInfo.Host,
		    connInfo.Port,
		    connInfo.Database,
	    )
    
	    db, err := sql.Open("clickhouse", connectionString)
	    if err != nil {
		    return nil, err
	    }
 
            rows, err := db.Query("SELECT * FROM example.table")
           if err != nil {
               log.Println("This is where I'd expect to see a non nil error")
          }

   }
```

### Error log
N/A

### Configuration

*OS:* Debian Buster

*Interface:* `database/sql`

*Driver version:* Latest

*Go version:*  1.19.2 

*ClickHouse Server version:*  22.10.1.15995

**Comment by gingerwizard** [comment]
Hi @niger-prequel thanks for this. So the issue is that clickhouse won't return an error immediately - which is what you're expecting by checking the err returned by Query. This is by design. 

Suppose the max execution time is 2s and the query takes, say 3 seconds to execute. Results can be streamed for the first 2s - ClickHouse doesn't know the query will take 3. On hitting the max execution time, an error will be returned via the rows.Err() property (once 2s is hit).

Now this behavior will differ if you're using HTTP over native protocol. In native, ClickHouse responds with a init empty block on which we base the structure of the rows and then streams blocks back with data. HTTP it tries to formulate the first  block - and errors.

A test best illustrates

```Go
func TestMaxExecutionTime(t *testing.T) {
	env, err := GetStdTestEnvironment()
	require.NoError(t, err)
	dsns := map[string]string{"Native": fmt.Sprintf("clickhouse://%s:%d?username=%s&password=%s", env.Host, env.Port, env.Username, env.Password),
		"Http": fmt.Sprintf("http://%s:%d?username=%s&password=%s", env.Host, env.HttpPort, env.Username, env.Password)}
	useSSL, err := strconv.ParseBool(clickhouse_tests.GetEnv("CLICKHOUSE_USE_SSL", "false"))
	require.NoError(t, err)
	if useSSL {
		dsns = map[string]string{"Native": fmt.Sprintf("clickhouse://%s:%d?username=%s&password=%s&secure=true", env.Host, env.SslPort, env.Username, env.Password),
			"Http": fmt.Sprintf("https://%s:%d?username=%s&password=%s&secure=true", env.Host, env.HttpsPort, env.Username, env.Password)}
	}
	for name, dsn := range dsns {
		t.Run(fmt.Sprintf("%s Protocol", name), func(t *testing.T) {
			dsn := fmt.Sprintf("%s&max_execution_time=2", dsn)
			conn, err := GetConnectionFromDSN(dsn)
			require.NoError(t, err)
			rows, err := conn.Query("SELECT sleep(3), number FROM numbers(10)")
			switch name {
			case "Http":
				assert.Error(t, err)
			case "Native":
				assert.NoError(t, err)
				for rows.Next() {
                                      // in this simple case no read is possible
				}
				assert.Error(t, rows.Err())
			}
		})
	}
}
```

Note we get no reads at all in the native case - as the sleep causes blocks to be formulated. With complex queries you might get blocks streamed back.

In general, id suggest you use the timeout functions of the client. This will cancel the query (sending a signal to the server) if a threshold is exceeded - example https://github.com/ClickHouse/clickhouse-go/blob/main/examples/std/context.go#L70

**Comment by gingerwizard** [comment]
Added a test https://github.com/ClickHouse/clickhouse-go/pull/806
