### ISSUE TITLE
Questions about the ch-go

### ISSUE THREAD

**Issue by chenlujjj** [ClickHouse/clickhouse-go#851]
Sorry for asking a question here, but I cannot find other open ways.

My question is:
(1) How to utilize the ch-go library? I have been using the `native` interface of lower version (v2.0.12), do I just need to upgrade `clickhouse-go` to higher version (>=2.3.0) and do nothing else?

(2) Performance comparison between whether using ch-go or not. I'm wondering how much it can imporve performance, especially in heavy writing.

**Comment by jkaflik** [comment]
Hi @chenlujjj it's fine to ask here

> How to utilize the ch-go library? I have been using the native interface of lower version (v2.0.12), do I just need to upgrade clickhouse-go to higher version (>=2.3.0) and do nothing else?

I do not expect any breaking changes compared to v2.0.12, but since this release was done by a previous maintainer, I can't say it will work out of the box.

While using `clickhouse-go` there is nothing to do with `ch-go` - i.e. `clickhouse-go` uses some protocol elements from `ch-go`, but it's not exposed externally.

> Performance comparison between whether using ch-go or not. I'm wondering how much it can imporve performance, especially in heavy writing.

I can't find any benchmarks done recently (we plan to automate client benchmarking in upcoming months), so can't back myself with numbers. `ch-go` API is column-oriented, so 1-1 compatible with CH protocol. `clickhouse-go` has an extra layer on top and exposes row-oriented API. Additionally, it has a `database/sql` driver implementation.

If you feel comfortable with column-oriented API, I recommend you to have a look at `ch-go`.

**Comment by chenlujjj** [comment]
@jkaflik Thanks for the detailed answer !  I will try to use high version `clickhouse-go` or `ch-go` and see how much I can benefit from it.

**Comment by jkaflik** [comment]
@chenlujjj let me close this issue. Happy to help you
