### ISSUE TITLE
Question mark (and ternary operators) in queries

### ISSUE THREAD

**Issue by Denvormine** [ClickHouse/clickhouse-go#878]
Hi! We just changed from v1 to v2 and we started to face problems with our queries which use ternary operators. Are they supported at all? If we use them with numeric/named parameters then we get MixedParams error (escaping them will result syntax error, they appear as \? in queries). If we use them with positional params then we must escape ternary question mark with backslash. So it appears that ternary operator only works if we use them with positional params and escape character. It's kind of strange behavior and I couldn't find any info about that.  Could you please clarify this problem: maybe we do something wrong and there's a change needed to be made when going from v1 to v2 in order to ternary operator to work?

P. S. question mark outside of scope of positional params and ternary operators (maybe in constant string) also kinda broken. It always considered as positional arg when not escaped and the only way to put it in query is to escape it, but then it will appear as escaped question mark.

**Comment by jkaflik** [comment]
Hi @Denvormine 

Bind functionality is deprecated since the 2.5.0 version and support for [native query parametersa](https://github.com/ClickHouse/clickhouse-go/pull/854) has been introduced.

If you use native query parameters, the bind feature will not be run and no issue with the ternary operator should arise.

A simple test to confirm:
```go
package issues

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
	clickhouse_tests "github.com/ClickHouse/clickhouse-go/v2/tests"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test878(t *testing.T) {
	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time": 60,
			"flatten_nested":     0,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)

	require.NoError(t, err)

	if !clickhouse_tests.CheckMinServerServerVersion(conn, 22, 8, 0) {
		t.Skip(fmt.Errorf("unsupported clickhouse version"))
		return
	}

	queryCtx := clickhouse.Context(context.Background(), clickhouse.WithParameters(clickhouse.Parameters{
		"intVar": "1",
	}))

	row := conn.QueryRow(queryCtx, "SELECT {intVar:Int64} = 1 ? 5 : 8")
	assert.NoError(t, row.Err())

	var actualVar uint8

	assert.NoError(t, row.Scan(&actualVar))
	assert.Equal(t, uint8(5), actualVar)
}
```

**Comment by Denvormine** [comment]
Okay, thank you for answer! We'll change our code to native then.

**Comment by bombsimon** [comment]
I assume it's not possible to combine native variables and `?` placeholders?

I faced this issue when querying/filtering on a column with a `?` in the name. What's the recommended way for something like this? Is it to do the last step as shown below and basically avoid both escaping column names and use positional arguments?

### Using columns with `?` but quoting them

```go
query := "SELECT `col?` FROM `tbl` WHERE 1 = 1 AND `col?` > ?"
conn.GetContext(
	ctx,
	&dst,
	query,
	lowerBound,
)
```

```sh
have no arg for param ? at last 2 positions
```

### Using native placeholders for complex column name only

```go
query := "SELECT {columnName:Identifier} FROM `tbl` WHERE 1 = 1 AND {columnName:Identifier} > ?"
conn.GetContext(
	clickhouse.Context(ctx, clickhouse.WithParameters(clickhouse.Parameters{
		"columnName":  "col?",
	})),
	&dst,
	query,
	time.Now(),
)
```

```sh
62, message: Syntax error: failed at position 64 (?): ?. Expected one of: CAST operator, ANY, ALL, NOT, INTERVAL, CASE, DATE, TIMESTAMP, tuple, collection of literals, array, number, literal, NULL, NULL, Bool, TRUE, FALSE, string literal, asterisk, qualified asterisk, compound identifier, identifier, COLUMNS matcher, COLUMNS, qualified COLUMNS matcher, function name, substitution, MySQL-style global variable
```

### Using native placeholders for both column name and arguments

Using native for both column name and arguments work, but now I have the extra step of having to convert all my data types to strings. For things like timestamps e.g. it's a bit cumbersome because I need to know exactly how it's parsed in ClickHouse, e.g. add this custom parsing format which doesn't have a constant in the `time` package.

```go
query := "SELECT {columnName:Identifier} FROM `tbl` WHERE 1 = 1 AND {columnName:Identifier} > {lowerBound:DateTime(9)}"
conn.GetContext(
	clickhouse.Context(ctx, clickhouse.WithParameters(clickhouse.Parameters{
		"columnName":  "col?",
		"lowerBound":  time.Now().Format("2006-01-02 15:04:05.999999999"),
	})),
	&dst,
	query,
	time.Now(),
)
```
