### ISSUE TITLE
insert query WithAsync option

### ISSUE THREAD

**Issue by jkaflik** [ClickHouse/clickhouse-go#896]
**Is your feature request related to a problem? Please describe.**

[Async insert](https://clickhouse.com/docs/en/optimize/asynchronous-inserts/) needs to be better documented and exposed to the user. 

**Describe the solution you'd like**
Add `WithAsync` to `QueryOption` that overrides query settings with `async_insert=1, wait_for_async_insert=0`

**Comment by jkaflik** [comment]
Async insert for native protocol is supported with inline INSERT query only. We can think about some data binding into inline query.

**Comment by mdonkers** [comment]
@jkaflik I'm currently running into this limitation as well (for the second time) and wonder what the actual problem is. For the `sql/database` interface is explicitly guarded: https://github.com/ClickHouse/clickhouse-go/blame/1cf2126cc12b07a39b9a7d1840e64bb6586de7d3/clickhouse_std.go#L238

But to my knowledge the 'binding' of arguments into the INSERT query should just result in a string such as `INSERT INTO my_table (a, b) VALUES (?, ?)` to be translated to `INSERT INTO my_table (a, b) VALUES ('foo', 'bar')`. Which is exactly the same as what you'd construct otherwise manually.

And actually the `bind` method (https://github.com/ClickHouse/clickhouse-go/blob/1cf2126cc12b07a39b9a7d1840e64bb6586de7d3/bind.go#L64) would be very helpful into translating e.g. Maps and Nested structs to a valid INSERT string.


So if there are no objections I would be happy to provide a PR to extend the AsyncInsert to do parameter binding (thinking about simply adding args to https://github.com/ClickHouse/clickhouse-go/blob/1cf2126cc12b07a39b9a7d1840e64bb6586de7d3/clickhouse.go#L168, such that `AsyncInsert(ctx context.Context, query string, wait bool, args ...any)` is backwards compatible with existing usage.

**Comment by mdonkers** [comment]
Proposal: https://github.com/ClickHouse/clickhouse-go/pull/1052

Seems to work. So would like to hear any feedback, if there are arguments against such a way forward.
